AuthSys/AuthSys/Controllers/Files1Controller.cs
using AuthSys.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.IO;

namespace AuthSys.Controllers
{
    public class Files1Controller : Controller
    {
        IHostingEnvironment _hostingEnvironment = null;
        
        public Files1Controller(IHostingEnvironment hostingEnvironment)
        {
            _hostingEnvironment = hostingEnvironment;
        }


        [HttpGet]
        public IActionResult CNLA_InnersRisk(string fileName = "")
        {
            FileClass fileObj = new FileClass();
            fileObj.Name = fileName;

            string path = $"{_hostingEnvironment.WebRootPath}\\files\\";
            int nId = 1;

            foreach (string pdfPath in Directory.EnumerateFiles(path, "*.pdf"))
            {
                fileObj.Files.Add(new FileClass()
                {
                    FileId = nId++,
                    Name = Path.GetFileName(pdfPath),
                    Path = pdfPath
                });
            }

            return View(fileObj);
        }

        [HttpPost]
        public IActionResult CNLA_InnersRisk(IFormFile file, [FromServices] IHostingEnvironment hostingEnvironment)
        {
            string fileName = $"{hostingEnvironment.WebRootPath}\\files\\{file.FileName}";
            using (FileStream fileStream = System.IO.File.Create(fileName))
            {
                file.CopyTo(fileStream);
                fileStream.Flush();

            }
            return CNLA_InnersRisk();
        }

        [HttpGet]
        public IActionResult CNLA_InnersExterior(string fileName = "")
        {
            FileClass fileObj = new FileClass();
            fileObj.Name = fileName;

            string path = $"{_hostingEnvironment.WebRootPath}\\files\\";
            int nId = 1;

            foreach (string pdfPath in Directory.EnumerateFiles(path, "*.pdf"))
            {
                fileObj.Files.Add(new FileClass()
                {
                    FileId = nId++,
                    Name = Path.GetFileName(pdfPath),
                    Path = pdfPath
                });
            }



            return View(fileObj);
        }

        [HttpPost]
        public IActionResult CNLA_InnersExterior(IFormFile file, [FromServices] IHostingEnvironment hostingEnvironment)
        {
            string fileName = $"{hostingEnvironment.WebRootPath}\\files\\{file.FileName}";
            using (FileStream fileStream = System.IO.File.Create(fileName))
            {
                file.CopyTo(fileStream);
                fileStream.Flush();

            }
            return CNLA_InnersExterior();
        }

        [HttpGet]
        public IActionResult CNLA_InnersLeadership(string fileName = "")
        {
            FileClass fileObj = new FileClass();
            fileObj.Name = fileName;

            string path = $"{_hostingEnvironment.WebRootPath}\\files\\";
            int nId = 1;

            foreach (string pdfPath in Directory.EnumerateFiles(path, "*.pdf"))
            {
                fileObj.Files.Add(new FileClass()
                {
                    FileId = nId++,
                    Name = Path.GetFileName(pdfPath),
                    Path = pdfPath
                });
            }



            return View(fileObj);
        }

        [HttpPost]
        public IActionResult CNLA_InnersLeadership(IFormFile file, [FromServices] IHostingEnvironment hostingEnvironment)
        {
            string fileName = $"{hostingEnvironment.WebRootPath}\\files\\{file.FileName}";
            using (FileStream fileStream = System.IO.File.Create(fileName))
            {
                file.CopyTo(fileStream);
                fileStream.Flush();

            }
            return CNLA_InnersLeadership();
        }

        public IActionResult PDFViewerNewTab(string fileName)
        {
            string path = _hostingEnvironment.WebRootPath + "\\files\\" + fileName;
            return File(System.IO.File.ReadAllBytes(path), "application/pdf");
        }

        [HttpGet]
        public IActionResult UploadPdfs(string fileName = "")
        {
            FileClass fileObj = new FileClass();
            fileObj.Name = fileName;

            string path = $"{_hostingEnvironment.WebRootPath}\\files\\";
            int nId = 1;

            foreach (string pdfPath in Directory.EnumerateFiles(path, "*.pdf"))
            {
                fileObj.Files.Add(new FileClass()
                {
                    FileId = nId++,
                    Name = Path.GetFileName(pdfPath),
                    Path = pdfPath
                });
            }

            return View(fileObj);
        }

        [HttpPost]
        public IActionResult UploadPdfs(IFormFile file, [FromServices] IHostingEnvironment hostingEnvironment)
        {
            string fileName = $"{hostingEnvironment.WebRootPath}\\files\\{file.FileName}";
            using (FileStream fileStream = System.IO.File.Create(fileName))
            {
                file.CopyTo(fileStream);
                fileStream.Flush();

            }
            return UploadPdfs();
        }

       
    }
}

AuthSys/AuthSys/Controllers/HomeController.cs
using AuthSys.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace AuthSys.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(/*ILogger<HomeController> logger*/)
        {
          //  _logger = logger;
        }

        public IActionResult Index()
        {
            return View("Index");
        }

        public IActionResult Privacy()
        {
            return View("Privacy");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
        public IActionResult CnlaInnersExterior()
        {
            return View("CnlaInnersExterior");
        }
        public IActionResult CnlaInnersRisk()
        {
            return View("CnlaInnersRisk");
        }
        public IActionResult CnlaInnersLeadership()
        {
            return View("CnlaInnersLeadership");
        }
    }
}

AuthSys/AuthSys/Views/Home/CnlaInnersExterior.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<p>
    <br />
    <h1>Introduction</h1>
    <br /><br />
    The purpose of this training manual is to cover the technical aspects of exterior landscaping from the
    perspective of management. We realize that managers cannot be technical experts in all areas of the
    operation, but they must have a general understanding of the aspects of technical issues that impact
    their ability to manage. A more detailed coverage of the technical knowledge needed by landscape
    contractors is covered in the following publications (available in both English and Spanish):
</p>
<br />
<ul>
    <li>Landscape Training Manual for Irrigation Technicians</li>
    <li>Landscape Training Manual for Maintenance Technicians</li>
    <li>Landscape Training Manual for Installation Technicians</li>
</ul>
<br />

<p>
    <h2>Chapter	1</h2><br /><br />
    <h3>Interpret	and	Implement	Landscape	Plans</h3><br /><br />
    <h5> Landscape	Specifications </h5><br /><br />
    </p>
<p>
    During	the	course	of	a	manager’s	day-to-day	work,	it	is	clear	that	landscape	specifications	need	to	be
    dealt	with,	both	to	develop	a	bid	for	a	project	and	to	provide	landscaping	crews	with	a	road	map	to
    follow	when	completing	the	project	itself.	To	ensure	that	the	company	will	be	successful	and	profitable,
    it	is	critical	to	be	able	to	accurately	read	and	understand	specifications.
    Landscape	specifications	refer	to	both	the	drawings	and	written	specifications that	accompany
    landscape	contracts.	Large	companies	normally	have	estimators	whose	job	it	is	to	understand	the
    specifications,	to	be	able	to	do	quantity	takeoffs	from	drawings,	and	to	develop	a	cost	to	carry	out	the
    project	on	the	basis	of	the	specifications	and	drawings.	Although	the	larger	companies	have	estimators,
    the	manager/owner	needs	to	have	a	good	understanding	of	specifications	to	enable	him	or	her	to
    review	the	work	carried	out	by	the	estimator.	In	smaller	companies,	it	is	very	often	the	owner/manager
    who	prepares	the	bids;	thus,	in	these	instances,	it	is	essential	that	the	owner/manager	have	a	clear
    understanding	of	the	drawings	and	specifications	in	order	to	bid	properly.
    The	goal	in	using	landscape	specifications	is	pretty	straightforward.	In	Canada,	large	dollar	tenders	will
    often	be	drafted	according	to	CCDC	standards	(Canadian	Construction	Documents	Committee,
    www.ccdc.org/home.html).	In	the	United	States,	standardized	contracts	are	available	from	the
    Association	of	General	Contractors	of	America,	and	contract	information	is	also	available	from	the
    National	Institute	of	Building	Sciences.	These	can	be	very	complex	documents	that	require	a	great	deal
    of	expertise	to	understand	and	to	comply	with	the	terms	and conditions	they	contain.
    We	will	concentrate	our	discussion	on	smaller	scale	projects,	which	will	not	be	as	complex,	but	which
    will	still	require	an	understanding	of	the	basic	components	and	concepts	of	specifications.	To	start,	let	us
    look	at	a	more	detailed	difference	between	drawings	and	written	specifications.	The	first	thing	to
    understand	is	that,	when	there	is	a	legal	problem,	written	specifications	take	precedence	over	drawings
    in	the	eyes	of	the	court.	Therefore,	the	written	specifications	cannot be	ignored	just	because	“they	are
    too	complicated,”	nor	should	they	be	viewed	as	“guides”	to	the	work	being	performed.
    Drawings	are	a	visual	representation	of	the	shapes,	location,	dimensions,	and	measurements	of	the
    work	to	be	done	on	a	particular	project.	Specifications	are	a	more	precise,	formal,	and	detailed
    description	of	the	work	to	be	done.	They	generally	include	the	way	the	work	is	to	be	done	and	include
    procedures,	the	materials	to	be	used,	and	the	quality	required.	Experience	will	show	that	a	combination
    of	good	drawings	and	good	specifications	makes	the	job	much	easier	to	bid	accurately	and	complete
    successfully.
</p>

AuthSys/AuthSys/Views/Home/CnlaInnersLeadership.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<p>
    <br />
    <h2>Chapter	1</h2><br /><br />
    <h3>Leadership	for	the	21st	Century</h3><br /><br />
     <h5> The	Role	of	Managers </h5><br /><br />
    </p>
<p>
    This	module	covers	the	leadership	aspects	of	management,	but	does	not	address	the	other	significant
    roles	that	managers	play in	planning,	organizing,	and	controlling	business	operations.	These	three
    aspects	of	management	are	covered	in	other	Business	Management	Training	Manuals,	including	the
    “Strategic	Planning	Manual,”	the	“Corporate	Financial	Management	Manual,”	and	the	“Human Resource
    Training	Manual.”	The	following	paragraphs	provide	a	brief	review	of	the	roles	of	managers	in	business
    today.
    All	companies	need	managers,	but	we	often	do	not	give	much	thought	to	what	is	the	true	role	of	a
    manager.	The	most	accepted	definition	of	management	is	“the	process	of	achieving	organizational	goals
    by	engaging	in	planning,	organizing,	leading,	and	controlling.”
    </p>

AuthSys/AuthSys/Views/Home/CnlaInnersRisk.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<p>
    <br />
    <h2>Chapter	1</h2><br /><br />
    <h3>Managing	Risk</h3><br /><br />
    </p>
   
<p>
    Risk	is	defined	as	“a	condition	in	which	there	is	a	possibility	of	an	adverse	deviation	from	a	desired
    outcome	that	is	expected	or	hoped	for.”	In	business,	including the	green	industry, the	outcomes	of
    unmanaged	or	poorly	managed	risk	produce	losses	in	company	assets,	earnings,	reputation,	and/or
    employee	productivity,	employee	safety and	well-being;	it	can	also	be	a	“black	hole”	consuming	huge
    amounts	of	management	time.	 Business	risk	presents	itself	in	many	ways;	the	typical	examples	of	risk
    that	most	businesses	think	of	are	fire,	natural	disasters,	theft,	damage	to	assets	(property,	offices,
    trucks),	and	third-party	liability. It	is	important	to	remember that there will	always	be	risk,	and	it	is
    equally important	you	learn	to	manage	your	risk	in	order	to	maximize	your	profit-potential.
    There	are	a	number	of	ways	that	risk	can	be	classified	to	make	it	easier	to	develop	risk	mitigation
    strategies.	One	way	is	to	categorize	the	risk	by	the	amount	of influence	the	business	owner	has	over	the
    risk—see	Figure	1 for	a	breakdown.
    </p>

AuthSys/AuthSys/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}


@{


}
<style>
    .gallery-view {
        align-content: center;
        padding-left: 100px;
      
    }
    .float-container {
        border: 3px solid #fff;
        padding: 20px;
    }

    .float-child {
        width: 50%;
        float: left;
        padding: 20px;
        border: 2px solid black;
    }
</style>



<div class="text-center">
    <br />
    <h1 class="display-4">Welcome To CNLA Doc-Sharing</h1>
</div><br />

      <div class="float-container">
          <div class="float-child">


              <a style="text-decoration:none;" href="@Url.Action("CNLA_InnersExterior","Files1")">

                  <img src="~/Folder.png" width="75px" />
                  CNLA - INNERS - EXTERIOR
              </a><br />


              <a style="text-decoration:none;" href="@Url.Action("CNLA_InnersRisk","Files1")">

                  <img src="~/Folder.png" width="75px" />
                  CNLA - INNERS - RISK
              </a><br />


              <a style="text-decoration:none;" href="@Url.Action("CNLA_InnersLeadership","Files1")">

                  <img src="~/Folder.png" width="75px" />
                  CNLA - INNERS - LEADERSHIP
              </a><br />
             
          </div>

          <div class="float-child">
              
              <a style="text-decoration:none;" href="@Url.Action("","")">

                  <img src="~/Folder.png" width="75px" />
                  To be Made...
              </a><br />
                  
                  <a style="text-decoration:none;" href="@Url.Action("","")">

                      <img src="~/Folder.png" width="75px" />
                      To be Made...
                  </a><br />
                  
                      <a style="text-decoration:none;" href="@Url.Action("","")">

                          <img src="~/Folder.png" width="75px" />
                          To be Made...
                      </a><br />
                 
          </div>
          </div>